/*
	Working through the postgresql tutorials
*/


-- ----------------------------------------------------------------------------------------------------
-- Section 1. Querying Data
-- ----------------------------------------------------------------------------------------------------

-- Select – show you how to query data from a single table.

SELECT first_name
FROM customer;

SELECT first_name
   , last_name
   , email
FROM customer;

-- returns all columns, not good practice to use *   
SELECT *
FROM customer;
	
-- basic expression
SELECT 5 * 3;

-- Column aliases – learn how to assign temporary names to columns or expressions in a query.

-- concatenate expression
SELECT first_name ||' '|| last_name full_name
	, email
FROM
	customer;

-- alias with spaces, MUST use double quotes
SELECT first_name ||' '|| last_name "full name"
FROM customer;

-- Order By – guide you on how to sort the result set returned from a query.

SELECT first_name
	, last_name
FROM customer
ORDER BY first_name ASC;

SELECT first_name
	, last_name
FROM customer
ORDER BY first_name ASC
	, last_name DESC;

-- order by expression(name length)
SELECT first_name
	, LENGTH(first_name) len
FROM customer
ORDER BY len DESC;

-- create a new table
CREATE TABLE sort_demo(
	num INT
);

-- insert some data
INSERT INTO sort_demo(num)
VALUES(1),(2),(3),(null);

SELECT num
FROM sort_demo
ORDER BY num NULLS FIRST;

-- Select Distinct  – provide you with a clause that removes duplicate rows in the result set.

CREATE TABLE distinct_demo (
	id serial NOT NULL PRIMARY KEY,
	bcolor VARCHAR,
	fcolor VARCHAR
);

INSERT INTO distinct_demo (bcolor, fcolor)
VALUES
	('red', 'red'),
	('red', 'red'),
	('red', NULL),
	(NULL, 'red'),
	('red', 'green'),
	('red', 'blue'),
	('green', 'red'),
	('green', 'blue'),
	('green', 'green'),
	('blue', 'red'),
	('blue', 'green'),
	('blue', 'blue');
	
SELECT
	id
	, bcolor
	, fcolor
FROM
	distinct_demo
	
SELECT DISTINCT bcolor
FROM distinct_demo
ORDER BY bcolor;

-- returns all unique combinations of selected columns
SELECT DISTINCT bcolor
	, fcolor
FROM distinct_demo
ORDER BY bcolor
	, fcolor;
	
-- distinct on takes the first distinct row based on the given column
SELECT DISTINCT ON (bcolor) bcolor
	, fcolor
FROM distinct_demo
ORDER BY bcolor
	, fcolor;

-- ----------------------------------------------------------------------------------------------------
-- Section 2. Filtering Data
-- ----------------------------------------------------------------------------------------------------

-- Where – filter rows based on a specified condition.

/*
Operator	Description
--------	-----------
=		  | Equal
>		  | Greater than
<		  | Less than
>=		  | Greater than or equal
<=		  | Less than or equal
<> or !=  | Not equal
AND		  | Logical operator AND
OR		  | Logical operator OR
IN		  | Return true if a value matches any value in a list
BETWEEN	  | Return true if a value is between a range of values
LIKE	  | Return true if a value matches a pattern
IS NULL	  | Return true if a value is NULL
NOT		  | Negate the result of other operators
*/

SELECT last_name
	, first_name
FROM customer
WHERE first_name = 'Jamie'
	AND last_name = 'Rice';
	
SELECT last_name
	, first_name
FROM customer
WHERE first_name IN ('Ann', 'Anne', 'Annie')

SELECT first_name
	, last_name
FROM customer
WHERE first_name LIKE 'Ann%'

SELECT first_name
	, LENGTH(first_name) name_length
FROM customer
WHERE first_name LIKE 'A%'
	AND LENGTH(first_name) BETWEEN 3 AND 5
ORDER BY name_length;

SELECT last_name
	, first_name
FROM customer
WHERE first_name LIKE 'Bra%' AND
	last_name <> 'Motley';


-- Limit – get a subset of rows generated by a query.

SELECT film_id
	, title
	, release_year
FROM film
ORDER BY film_id
LIMIT 5 --OFFSET 3
;

-- returns top 10 most expensive films
SELECT film_id
	, title
	, rental_rate
FROM film
ORDER BY rental_rate DESC
LIMIT 10;

-- Fetch– limit the number of rows returned by a query.
-- same function as limit but works globally, use when you need it to funtion with other systems

SELECT film_id
    , title
FROM film
ORDER BY title
--OFFSET 5 ROWS
FETCH FIRST 5 ROW ONLY;

-- In – select data that matches any value in a list of values.

SELECT 2 IN (1, 2, 3)

SELECT customer_id
	, rental_id
	, return_date
FROM rental
WHERE customer_id IN (1, 2)
-- Equivalent where statement:
-- Where customer_id = 1 OR customer_id = 2
ORDER BY return_date DESC;

-- IN with a subquery
SELECT customer_id
FROM rental
WHERE CAST (return_date AS DATE) = '2005-05-27'
ORDER BY customer_id;

SELECT customer_id
	, first_name
	, last_name
FROM customer
WHERE customer_id IN(
	SELECT customer_id
	FROM rental
	WHERE CAST (return_date AS DATE) = '2005-05-27'
	)
ORDER BY customer_id;

-- Between – select data that is a range of values.

SELECT customer_id
	, payment_id
	, amount
FROM payment
WHERE amount BETWEEN 8 AND 9;
	
SELECT customer_id
	, payment_id
	, amount
	, payment_date
FROM payment
WHERE payment_date BETWEEN '2007-02-07' AND '2007-02-15';

-- Like – filter data based on pattern matching.

SELECT first_name
	, last_name
FROM customer
WHERE first_name LIKE '_her%'
ORDER BY  first_name;

-- ILIKE postgres operator is case insensitive
SELECT first_name
	, last_name
FROM customer
WHERE first_name ILIKE 'BAR%';

-- Is Null – check if a value is null or not.

CREATE TABLE contacts(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(15),
    PRIMARY KEY (id)
);

-- The following statement inserts two contacts, one has a phone number and the other does not:
INSERT INTO contacts(first_name, last_name, email, phone)
VALUES ('John','Doe','john.doe@example.com',NULL),
    ('Lily','Bush','lily.bush@example.com','(408-234-2764)');

-- ----------------------------------------------------------------------------------------------------
-- Section 3. Joining Multiple Tables
-- ----------------------------------------------------------------------------------------------------
-- Joins – show you a brief overview of joins in PostgreSQL.
-- Table aliases – describes how to use table aliases in the query.
-- Inner Join – select rows from one table that has the corresponding rows in other tables.
-- Left Join – select rows from one table that may or may not have the corresponding rows in other tables.
-- Self-join – join a table to itself by comparing a table to itself.
-- Full Outer Join – use the full join to find a row in a table that does not have a matching row in another table.
-- Cross Join – produce a Cartesian product of the rows in two or more tables.
-- Natural Join – join two or more tables using implicit join conditions based on the common column names in the joined tables.

-- ----------------------------------------------------------------------------------------------------
-- Section 4. Grouping Data
-- ----------------------------------------------------------------------------------------------------
-- Group By – divide rows into groups and applies an aggregate function on each.
-- Having – apply conditions to groups.

-- ----------------------------------------------------------------------------------------------------
-- Section 5. Set Operations
-- ----------------------------------------------------------------------------------------------------
-- Union – combine result sets of multiple queries into a single result set.
-- Intersect – combine the result sets of two or more queries and returns a single result set that has the rows appear in both result sets.
-- Except – return the rows in the first query that does not appear in the output of the second query.

-- ----------------------------------------------------------------------------------------------------
-- Section 6. Grouping sets, Cube, and Rollup
-- ----------------------------------------------------------------------------------------------------
-- Grouping Sets  – generate multiple grouping sets in reporting.
-- Cube – define multiple grouping sets that include all possible combinations of dimensions.
-- Rollup – generate reports that contain totals and subtotals.

-- ----------------------------------------------------------------------------------------------------
-- Section 7. Subquery
-- ----------------------------------------------------------------------------------------------------
-- Subquery – write a query nested inside another query.
-- ANY  – retrieve data by comparing a value with a set of values returned by a subquery.
-- ALL – query data by comparing a value with a list of values returned by a subquery.
-- EXISTS  – check for the existence of rows returned by a subquery.

-- ----------------------------------------------------------------------------------------------------
-- Section 8. Common Table Expressions
-- ----------------------------------------------------------------------------------------------------
-- PostgreSQL CTE – introduce you to PostgreSQL common table expressions or CTEs.
-- Recursive query using CTEs – discuss the recursive query and learn how to apply it in various contexts.

-- ----------------------------------------------------------------------------------------------------
-- Section 9. Modifying Data
-- ----------------------------------------------------------------------------------------------------
-- In this section, you will learn how to insert data into a table with the INSERT statement, modify existing data with the UPDATE statement, and remove data with the DELETE statement. Besides, you learn how to use the upsert statement to merge data.
-- Insert – guide you on how to insert a single row into a table.
-- Insert multiple rows – show you how to insert multiple rows into a table.
-- Update – update existing data in a table.
-- Update join – update values in a table based on values in another table.
-- Delete – delete data in a table.
-- Upsert – insert or update data if the new row already exists in the table.

-- ----------------------------------------------------------------------------------------------------
-- Section 10. Transactions
-- ----------------------------------------------------------------------------------------------------
-- PostgreSQL Transactions – show you how to handle transactions in PostgreSQL using BEGIN, COMMIT, and ROLLBACK statements.

-- ----------------------------------------------------------------------------------------------------
-- Section 11. Import & Export Data
-- ----------------------------------------------------------------------------------------------------
-- You will learn how to import and export PostgreSQL data from and to CSV file format using the copy command.
-- Import CSV file into Table – show you how to import CSV file into a table.
-- Export PostgreSQL Table to CSV file – show you how to export tables to a CSV file.

-- ----------------------------------------------------------------------------------------------------
-- Section 12. Managing Tables
-- ----------------------------------------------------------------------------------------------------
-- In this section, you will start exploring the PostgreSQL data types and show you how to create new tables and modify the structure of the existing tables.
-- Data types – cover the most commonly used PostgreSQL data types.
-- Create a table – guide you on how to create a new table in the database.
-- Select Into & Create table as– shows you how to create a new table from the result set of a query.
-- Auto-increment column with SERIAL – uses SERIAL to add an auto-increment column to a table.
-- Sequences – introduce you to sequences and describe how to use a sequence to generate a sequence of numbers.
-- Identity column – show you how to use the identity column.
-- Alter table – modify the structure of an existing table.
-- Rename table – change the name of the table to a new one.
-- Add column – show you how to use add one or more columns to an existing table.
-- Drop column – demonstrate how to drop a column of a table.
-- Change column data type – show you how to change the data of a column.
-- Rename column – illustrate how to rename one or more columns of a table.
-- Drop table – remove an existing table and all of its dependent objects.
-- Truncate table – remove all data in a large table quickly and efficiently.
-- Temporary table – show you how to use the temporary table.
-- Copy a table – show you how to copy a table to a new one.

-- ----------------------------------------------------------------------------------------------------
-- Section 13. Understanding PostgreSQL Constraints
-- ----------------------------------------------------------------------------------------------------
-- Primary key – illustrate how to define a primary key when creating a table or adding a primary key to an existing table.
-- Foreign key – show you how to define foreign key constraints when creating a new table or add foreign key constraints for existing tables.
-- CHECK constraint – add logic to check value based on a Boolean expression.
-- UNIQUE constraint – make sure that values in a column or a group of columns are unique across the table.
-- NOT NULL constraint – ensure values in a column are not NULL.

-- ----------------------------------------------------------------------------------------------------
-- Section 14. PostgreSQL Data Types in Depth
-- ----------------------------------------------------------------------------------------------------
-- Boolean – store TRUE and FALSE values with the Boolean data type.
-- CHAR, VARCHAR and TEXT – learn how to use various character types including CHAR, VARCHAR, and TEXT.
-- NUMERIC – show you how to use NUMERIC type to store values that precision is required.
-- Integer – introduce you to various integer types in PostgreSQL including SMALLINT, INT and BIGINT.
-- DATE  – introduce the DATE data type for storing date values.
-- Timestamp – understand timestamp data types quickly.
-- Interval – show you how to use interval data type to handle a period of time effectively.
-- TIME – use the TIME datatype to manage the time of day values.
-- UUID – guide you on how to use UUID datatype and how to generate UUID values using supplied modules.
-- Array – show you how to work with the array and introduces you to some handy functions for array manipulation.
-- hstore – introduce you to data type which is a set of key/value pairs stored in a single value in PostgreSQL.
-- JSON – illustrate how to work with JSON data type and shows you how to use some of the most important JSON operators and functions.
-- User-defined data types – show you how to use the CREATE DOMAIN and CREATE TYPE statements to create user-defined data types.

-- ----------------------------------------------------------------------------------------------------
-- Section 15. Conditional Expressions & Operators
-- ----------------------------------------------------------------------------------------------------
-- CASE – show you how to form conditional queries with CASE expression.
-- COALESCE – return the first non-null argument. You can use it to substitute NULL by a default value.
-- NULLIF – return NULL if the first argument equals the second one.
-- CAST – convert from one data type into another e.g., from a string into an integer, from a string into a date.

/*
This is for psql commands so won't be in pgadmin

Section 16. PostgreSQL Utilities
psql commands – show you the most common psql commands that help you interact with psql faster and more effectively.
*/

-- ----------------------------------------------------------------------------------------------------
-- Section 17. PostgreSQL Recipes
-- ----------------------------------------------------------------------------------------------------
-- How to compare two tables – describe how to compare data in two tables in a database.
-- How to delete duplicate rows in PostgreSQL – show you various ways to delete duplicate rows from a table.
-- How to generate a random number in a range  – illustrate how to generate a random number in a specific range.
-- EXPLAIN statement– guide you on how to use the EXPLAIN statement to return the execution plan of a query.
-- PostgreSQL vs. MySQL – compare PostgreSQL with MySQL in terms of functionalities.